# Generated by Django 5.1.1 on 2024-10-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montadora', models.CharField(choices=[('1', 'AUDI'), ('2', 'BMW'), ('3', 'CHEVROLET - GM'), ('4', 'FIAT'), ('5', 'FORD'), ('6', 'HONDA'), ('7', 'HYUNDAI'), ('8', 'VOLKSWAGEN')], max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('cor', models.CharField(choices=[('1', 'BRANCO'), ('2', 'AMARELO'), ('3', 'AZUL'), ('4', 'PRATA'), ('5', 'PRETO'), ('6', 'VERMELHO')], max_length=50)),
            ],
        ),
    ]
